### ISSUE TITLE
Xcode 7.1 Playgrounds not showing evaluation on right

### ISSUE THREAD

**Issue by dylansm** [XVimProject/XVim#874] opened 2015-10-28 14:26 UTC
When I have the XVim plugin installed, a new default Playground should show "Hello, playground" on the right. It doesn't. When I uninstall the plug-in, it shows on the right, as expected.

This is the simplest example. Fact is, nothing evaluates on the right when the plug-in is installed.

**Comment by GregIngelmo** [comment] 2015-10-28 20:41
Same here

**Comment by kouky** [comment] 2015-10-28 22:56
:+1: new playground with "Hello World", nothing printed by the REPL. Remove Xvim and the REPL starts printing again.

**Comment by mudox** [comment] 2015-10-28 23:41
Confirmed

**Comment by eriknelson** [comment] 2015-10-29 18:48
+1 here, xvim definitely breaks the playground eval.

**Comment by oldMrCoder** [comment] 2015-10-31 04:15
+1

**Comment by skf321** [comment] 2015-10-31 05:04
lucky to find a answer here

**Comment by stoneros** [comment] 2015-11-06 02:56
Confirmed!

**Comment by JugglerShu** [comment] 2015-11-06 03:17
I have investigated this problem. I already know rough reason of this problem but still don't know how to really fix this without disabling XVim.
Since I have to write some new methods to override default Playground behavior it may take a little time.
Sorry for waiting.

**Comment by ZillaG** [comment] 2015-11-07 05:50
How can I disable XVim temporarily?

**Comment by JugglerShu** [comment] 2015-11-07 05:57
Simply you can't (to workaround this problem).

**Comment by zef** [comment] 2015-11-07 05:57
@ZillaG you can temporarily move the `XVim.xcplugin` file from the `~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/` directory to another location (like just up a folder or something), then re-launch Xcode. To reinstall just move it back and relaunch.

**Comment by ZillaG** [comment] 2015-11-07 05:59
Ok I'll do that. Disabling it (Editor->XVim->toggle eneable/disable) doesn't work since the plugin is still there. Thanks.

**Comment by JugglerShu** [comment] 2015-11-07 06:19
I made the temporary fix for this problem. Use develop branch for now. It still has several problems but should fix right pane problem in playground. Please use `set blinkcursor` workaround for cursor problem.

**Comment by zef** [comment] 2015-11-07 06:20
@JugglerShu you are amazing! Thank you so much for all your hard work!

**Comment by JugglerShu** [comment] 2015-11-07 06:28
I don't use Playground much so I can't recognise what is not usual in Playground. So please report if you still have any critical problems in Playground.

**Comment by kouky** [comment] 2015-11-07 07:27
@JugglerShu thanks so much for all your amazing work :sparkles:

**Comment by ZillaG** [comment] 2015-11-07 12:53
Thanks!

(Sent from my iPhone)

**Comment by GregIngelmo** [comment] 2015-11-08 22:00
Confirmed fix. Evaluations appear on the right again

**Closed** 2015-11-10 09:32 UTC
