### ISSUE TITLE
Comment selection and move to next line...

### ISSUE THREAD

**Issue by patniemeyer** [XVimProject/XVim#848] opened 2015-10-21 15:02 UTC
When XVim is active using command-/ to comment a line does not move to the next line as it does in the default editor.  This makes the comment shortcut much less useful because you can't just repeatedly hit the key to comment out multiple lines.  I'm aware that one can comment with a selection but that is not as friendly.  One reason for this is that the visual selection indicator is not a good indicator of "lines" but rather characters.  e.g. if you are in col zero that line is selected even though there is no visual indication of it... So you always have to think about whether you are a line too far before commenting.  And I think it's just an extra keystroke or two that doesn't need to be there.  Thanks.

**Comment by SixFiveSoftware** [comment] 2015-10-21 15:06
@patniemeyer Do you use Shift+V or just V to visually select lines to comment? I use Shift+V to ensure I get the line, not just a starting character point...helps me mentally know that I've got the line no matter what.

**Comment by neybis** [comment] 2015-10-21 15:07
I believe this is because you are running the command from normal mode. Try command-/ from insert mode and it seems to work as Xcode does by default.

**Comment by neybis** [comment] 2015-10-21 15:08
I'm not sure how you are getting the Xcode behavior you are seeing. When I uninstall the XVim plugin and run Xcode with its default, Command-/ never moves to the next line.

Is this an Xcode 7 thing (I'm on Xcode 6)??

**Comment by SixFiveSoftware** [comment] 2015-10-21 15:14
It still doesn't move the cursor to the next line for me when using Shift+V for multiple line commenting, but I don't care about that because I've used Visual mode to select the lines I want to comment. Using Shift+V then J or K to go up or down to select the lines, then Cmd+/ to comment has just become part of my flow. I'm not saying that XVim shouldn't have the described behavior of this issue, just offering another way to interact that I've found helpful if it'll help.

**Comment by patniemeyer** [comment] 2015-10-21 15:15
Thanks - I hadn't thought of Shift+V and that does technically help, but it still feels like "more work" to me mentally than just mashing command+/ a few times.  I think that's partly because you have to think about the state you are in and partly because commenting out one line is different from commenting out two or a few...  Especially given that for larger regions I'd probably just use block comments ...

**Comment by neybis** [comment] 2015-10-21 15:46
For things Vim does, we obviously want to mimic that as much as possible and should prefer vim behavior to Xcode. For things Xcode does that Vim doesn't, we should try to keep Xcode's functionality and not introduce our new XVim only functionality.

That being said, if Xcode moves to the next line XVim should, too, because Vim never had this functionality and we would want to mimic Xcode in this case. However, I am unable to confirm this behavior with Xcode. Can you please state the version of Xcode that you are using? Perhaps some of our users can confirm that their Xcode does indeed behave in the way you described (moving to the next line after Command-/)??

(If Xcode's behavior can be confirmed, we should keep this open so we can address it at _some_ point.)

**Comment by rkam** [comment] 2015-10-21 16:40
fyi: I just tried this and it didn't change lines.  The insertion point doesn't change either.  It just entered two / at BoL.

Xcode Version 7.0.1 (7A1001)

(Personally I would prefer it to change lines to do the multi-line repetitive commenting, but I can see usefulness with this approach too.)

**Comment by neybis** [comment] 2015-10-21 19:08
@rkam Thanks for testing this out! Wasn't sure if this was something added in Xcode 7 as I'm on 6 but thanks again for confirming that.

*With some of this testing now out of the way:*
I, as a user, agree that this feature/functionality could prove useful in Xcode/XVim. My concern in adding this to XVim is in the time investment; not only in the development of the feature itself, but also in it's maintenance.

Typically speaking, the less code we can write the better. If we can allow Apple to maintain certain features for us, it is preferred. "Jump To Definition" is a great example of this. The amount of time it would take, not only to implement this but to keep it up to date with clang's ever changing API, is expensive.

If we were to implement a feature like this, our customers/users would come to expect it. This could break any time Xcode changes the way this Command-/ feature works. They could remove it entirely... then we'd have to implement it from scratch ourselves and we are straying from what XVim is; a plug-in for adding Vim behavior to Xcode, not add useful feature 'Y' to Xcode. I would rather see the ability to map a series of vim commands to a keypress fill this void. This is how it would be done in Vim! :) If you want a keyboard shortcut to perform vim commands 'x', 'y', 'z' then right a key mapping to do just that. I'm not sure if our key mappings work this well, but in theory they could.

Wrapping this conversation up, doing something that neither Xcode nor Vim does is not something that should be taken lightly. Again, we are a plugin to mimic Vim in Xcode not a plugin to add useful features to Xcode in general. In a perfect world, if this functionality was desired by enough users, Xcode would implement it themselves. And I would go so far as to say Apple has deemed this behavior is **not** desired. So I, as an engineer/project manager, would have to decline the request for this feature/functionality. If Xcode ever starts doing it, we will pick up the change automagically. Obviously, this is an open-source project and this is up for discussion but I think this is the kind of functionality that belongs in another plugin as neither Xcode nor Vim has this functionality.

**Comment by patniemeyer** [comment] 2015-10-22 14:13
Guys, I apologize, I would have sworn that was the default XCode behavior.  I guess I was remembering Intellij's behavior.  BTW, I might have noticed my mistake but I have no menu item to toggle XVim on/off easily.  I don't want to mix topics here but FYI.

**Comment by neybis** [comment] 2015-10-22 14:23
No worries man! Like I said, it would be a really nice thing to do. Surprised Xcode isn't already doing this. And I thought more about my comment last night. I guess we are kind of trying to become a better Xcode editor; it's just that our editor happens to mimic vim in most cases (but not all). So perhaps this isn't that far out of the reach of the scope of this plugin. My biggest concern is honestly the maintainability of the code as anytime Xcode changes their functionality it could break ours.

All that being said and addressing your menu problems for toggling; that is currently only in the head of develop, not master. What branch are you working off of? I, too, really wanted to ability to toggle this on and off. I've only tested with Xcode 6.1 and 6.4 but it seems to be working in the menus there.

**Comment by JugglerShu** [comment] 2015-11-17 13:21
I close this. If you still have menu item problem please make another issue.

**Closed by JugglerShu** 2015-11-17 13:21 UTC
