### ISSUE TITLE
EX command obscured coming from visual mode

### ISSUE THREAD

**Issue by lando2319** [XVimProject/XVim#905] opened 2015-12-14 19:01 UTC
From Visual Mode with Code highlighted, Pressing ":" moves the cursor to the Command Line area but the word "VISUAL" obstructs the command-line (see screenshot).

Big Time XVim Fan.
![vimvissue](https://cloud.githubusercontent.com/assets/2363722/11790699/caed8eea-a262-11e5-8c69-a94a1cab1ae2.png)

**Comment by regnerjr** [comment] 2015-12-16 22:16
Thanks for reporting.

Duplicate of #893.

**Closed** 2015-12-23 19:54 UTC
