### ISSUE TITLE
line moving feature is not work sometimes

### ISSUE THREAD

**Issue by BigPa** [XVimProject/XVim#908] opened 2015-12-22 14:55 UTC
I want to go to line 40 of a source file, I typed `40gg` in normal mode. And nothing happens.

But goto line 55 like `55gg` works.

Xcode Version 7.1.1 (7B1005)
OS X El Capitan 10.11.1
Latest XVim (I removed local repo and cloned again)

Shall I update my Xcode or OS X? 
(For some reasons, I can't update them in a period of time.)

**Comment by JugglerShu** [comment] 2015-12-30 16:37
There was an issue related to G and gg previously and it should be fixed already.
If you are using the latest master branch and still have the problem, add more information about the bug like, what kind of text you have on the line 40, and the line 55.

Also I would like you to investigate the issue more to reproduce the bug. (Just 40gg or 55gg are working in my environment)

**Comment by BigPa** [comment] 2015-12-31 04:08
When I pressed number key (normal mode), something will appear in the bottom right corner of editor area.
Like when I want to type `45gg`(goto line 45):
- Type `4`, it looks like `NUM4`.
- Type `5`, it looks like `NUM4NUM5`.
- Type `g`, it looks like `NUM4NUM5g`
- Type `g` again, all of them disappeared, and the cursor moved to line 45.

**BUT** if I want to goto line 40 and type `40gg`,
- Type `4`, it looks like `NUM4`.
- Type `0`, **the `NUM4` disappeared**
- Type `g`, it looks like `g`
- Type `g` again, all of them disappeared, and the cursor moved to line 1.

Maybe there is something wrong with number 0.

**Comment by JugglerShu** [comment] 2015-12-31 07:27
I can't reproduce the bug. I can see `NUM0` when I type 4 and 0.
I feel you are using a little old XVim version. Can you try to rebuild your XVim and restart Xcode again?

**Comment by BigPa** [comment] 2016-01-04 07:58
XVim version is the latest, the bug is because of my `xvimrc`. I removed them.

**Comment by JugglerShu** [comment] 2016-01-04 08:30
I close this. If you still have problem reopen please.

**Closed** 2016-01-04 08:30 UTC
