### ISSUE TITLE
Text stretching when scrolling

### ISSUE THREAD

**Issue by keith** [XVimProject/XVim#882] opened 2015-11-14 01:07 UTC
I'm seeing this quite often when scrolling:

<img width="538" alt="screen shot 2015-11-13 at 16 58 58" src="https://cloud.githubusercontent.com/assets/283886/11161099/ff571dce-8a28-11e5-973e-c21e2d492042.png">

**Comment by luomuwen** [comment] 2015-11-14 07:53
me too

**Comment by JugglerShu** [comment] 2015-11-14 11:17
I can't reproduce this.
Please provide the environment information.
OS version, Xcode version, branch or commit you are using to build XVim.

**Comment by JugglerShu** [comment] 2015-11-14 11:50
BTW, are you scrolling with mouse??

**Comment by keith** [comment] 2015-11-14 17:00
Yes this happens when scrolling with the mouse.

**Comment by JugglerShu** [comment] 2015-11-14 21:43
What's your environment? OS version, Xcode version, branch or commit you are using to build XVim?

**Comment by keith** [comment] 2015-11-15 05:27
I'm on 10.11.1, Xcode 7.1.1 and the newest master of XVim ( 26bdd1a33f624216163ba77a92ba495a508f0555)

**Comment by floorish** [comment] 2015-11-16 16:36
Same issue here, see https://github.com/XVimProject/XVim/issues/867#issuecomment-155375309

Setting OSX scrollbars to "Always" in Settings -> General does solve the issue for me.

Xcode: Version 7.1 (7B91b)
OSX: Version 10.10.5 (14F27)
XVim: latest develop (26bdd1a) and Alcatraz version 
XVimrc: https://github.com/floorish/dotfiles/blob/master/xvimrc
No other plugins loaded

**Comment by keith** [comment] 2015-11-16 16:49
I have scroll bars set to always already and still see this.

**Comment by floorish** [comment] 2015-11-16 17:27
@keith, weird I definitely didn't get it when I changed the scrollbars. Have you tried switching to Automatic?

**Comment by JugglerShu** [comment] 2015-11-16 21:33
Hm... I've been trying to reproduce this but it never happens. Including, scroll bar settings, Xcode versions (6.4, 7.1 and 7.1.1) and xvimrc file you provided, Alcatraz ... nothing helped.
I think we need some more specific information. I'll keep trying to reproduce so please let me know if you find something.

**Comment by keith** [comment] 2015-11-16 23:49
It does seem to be fixed when scrollbars are set to automatic. Which is strange. I'll post anything if I can make it reproducible! ¯\_(ツ)_/¯

**Comment by floorish** [comment] 2015-11-17 10:18
@JugglerShu I can reproduce it with the following steps (9 out of 10 times):

- open Xcode project
- press "o" to go to insert mode and create a new line
- ESC to go to normal mode
- scroll

Issue does not occur when:
- scrolling when still in insert mode after pressing "o"

**Comment by JugglerShu** [comment] 2015-11-17 13:27
Still can't. I tried it in 2 Macs I have but it never happens...

**Comment by JugglerShu** [comment] 2015-11-17 13:33
BTW, do you have #870 problem? I mean do you see any characters or rectangle is drawn out side of the text view? If so, it is very likely that you are using old XVim version. (In 26bdd1a commit this problem is fixed so if you still have this problem, please reinstall XVim according to https://github.com/XVimProject/XVim/issues/757#issuecomment-106301119 )

**Comment by floorish** [comment] 2015-11-17 13:51
No, I'm using the latest development branch (now https://github.com/XVimProject/XVim/commit/bc9c60c9b74a404ba6d968d614a095694ff8463d).
I uninstalled Xvim and run in debug mode currently.

I experienced the #870 problem as well, but it has been solved for me since the fix.

**Comment by floorish** [comment] 2015-11-17 14:21
Ok, here are some more testing results. I tried XVim on a fresh Xcode 7.1 (no .xvimrc) on El Capitan:
Scrollbars always on -> smeared text
Scrollbars automatic -> no issue

Whereas on my other mac with Yosemite, Xcode 7.1
Scrollbars always on -> no issue
Scrollbars automatic -> smeared text

I'm not sure if this is in anyway useful though...

**Comment by pebble8888** [comment] 2015-11-19 11:36
Hi @JugglerShu 

I reproduced this behaviour.
MacBookAir Eealy 2015 13inch 
OSX 10.10.5
Xcode7.1.1
lastest Xvim develop branch 5be0de0

0) .xvimrc is empty
1) press "o" to go to insert mode and press ESC 
2) scroll slowly by track pad

This behaviour doesn't happen in my develop branch f052d65

I think probably this commit affect it.
```
commit 577d852d5cf2a9af6e6304f27d8bd00b9e1f0857
Author: pebble8888 <pebble8888@gmail.com>
Date:   Thu Jun 25 20:00:59 2015 +0900

    Revert "Added theming on XVimStatusLine, fixed clipping bug with DVTSourceTextView when selecting code blocks in gutter"
    
    This reverts commit 1ca60f5fdac29d3e28829eac8cc5a2dad47b0bc9.
```

![xvimbug](https://cloud.githubusercontent.com/assets/1704383/11269627/6749cf40-8efb-11e5-9f5a-26018d7e739c.gif)

**Comment by JugglerShu** [comment] 2015-11-19 12:46
@pebble8888 Thank you for the information. But the problem is that even we know the commit that makes this bug I can't tell which code is actually wrong.
I still can't reproduce that behaviour. I know that the code around caret drawing does something wrong but I can't tell which part is wrong if I can't reproduce this by myself.

I would like you to find out which code is actually the cause of this in the latest commit.
My current guess is in DVTSourceTextView+XVim.m around 

        NSGraphicsContext *context = [NSGraphicsContext currentContext];
        [context saveGraphicsState];
        [[NSBezierPath bezierPathWithRect:[self visibleRect]] setClip];
        [window drawInsertionPointInRect:glyphRect color:aColor];
        [context restoreGraphicsState];

I think `setClip` might doing something wrong here.

I also would like to take a log of xvim_drawRect when scrolling. My guess is the function is not called when scrolling (or dirtyRect argument is smaller than visibleRect).

**Comment by keith** [comment] 2015-11-19 21:37
Until we can figure this out you can change only Xcode's scroll bar styles to "when scrolling" with:

```
defaults write com.apple.dt.Xcode AppleShowScrollBars -string "WhenScrolling"
```

**Comment by JugglerShu** [comment] 2015-11-20 10:27
I finally could reproduce the behaviour. I'll see what is the problem.
(I still don't know why I can reproduce this now. I use another MacBookPro and it is reproduce on that machine)

**Comment by JugglerShu** [comment] 2015-11-20 15:23
Just a record for debugging. I found the difference between logs when this happens and not.
When **scrolling up** and when this doesn't happen, drawRect's dirtyRect argument is like

       dirtyRect(0.000000,155.000000,717.000000,618.000000) // x,y, width, height

And when this does happen, dirtyRect is like

       dirtyRect(0.000000, 450.000000,717.000000, **1.000000**) // x,y, width, height

This means that, first dirtyRect expresses whole view area while second one expresses just a 1 point size (height) of area.
Because this log is from when scrolling up, second dirtyRect means just a newly visible area and it tries to redraw that area.

As scrolling more, drawRect is called again and again, but when it doens't happen, dirtyRect's height is always full height of the visible area. On the other hand, when it happens, dirtyRect's height is something like 1.0 or 2.0 or 3.0 (which is the height of the newly visible area).

Thermally both should work properly but in some reason it doesn't work well in second log version.

I still don't know what makes this difference.

**Comment by floorish** [comment] 2015-11-20 16:22
Can confirm that; Depending on the System scrollbar setting, drawRect will update full screen height or update only single pixel line. However it does seem "correct", in that if I scroll a single pixel, it should only draw that new pixel.

**Comment by JugglerShu** [comment] 2015-11-20 16:53
@floorish 
Yea, just updating newly visible area is correct. But I see the difference there.

Here is height of the dirtyRect in different environments.
Env1 is one in which I can reproduce the bug.
Env2 is one in which I can not reproduce the bug.
 
ScrollSetting  |   "Automatically..." | "When scrolling" | "Always"
------------------|-------------------------|-------------------------|-------------------
    Env1(bug) |  Single  Pixel        |  Single Pixel         | Full height
    Env2         |   Full height          | Full height             | Single Pixel

As you can see they are completely opposite.

I'm not thinking that just redrawing single pixel is wrong, but I feel that I can get some hints from there.

**Comment by JugglerShu** [comment] 2015-11-20 17:13
I think I got the hint. I think this bug happens only in Retina display.
The dirtyRect has `y` of less than 1.0 point granularity when it is Retina display.

dirtyRect(0.000000, **77512.500000** ,1080.000000,2.000000)

Let me know if you can reproduce this in non-Retina display.
I still don't know where is the right place we should fix, though. ( I don't even think 0.5 point granularity is wrong. )

**Comment by floorish** [comment] 2015-11-20 17:41
I have an iMac (non-retina, Yosemite), which behaves like your Env1
And a Macbook Air (non-retina, El Capitan), which behaves like your Env2

**Comment by JugglerShu** [comment] 2015-11-20 17:49
Hm... then there is no common thing among the reproducible environment...

**Comment by floorish** [comment] 2015-11-20 17:57
My Objective-C debugging skills are not very good. Can you take a look at 

scrollView.contentView.copiesOnScroll

https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSClipView_Class/#//apple_ref/occ/instp/NSClipView/copiesOnScroll

**Comment by floorish** [comment] 2015-11-20 18:00
BTW, @pebble8888  could you change your gif into an external link? My Safari browser really struggles with loading this page ;)

**Comment by pebble8888** [comment] 2015-11-20 23:47
@floorish, I removed gif. I'm sorry for uploading big gif.

**Comment by pebble8888** [comment] 2015-11-21 08:04
@JugglerShu 
I pushed `fix_882` branch.
The patch has erased the bug.
Generally speaking, direct calling drawRect is dangerous.
Normally as calling setNeedsDiplay tell OS X the rectangle dirty, OS X call drawRect at its appropriate timing.

I don't know whether this patch break all relating features, for example blink cursor.

**Comment by JugglerShu** [comment] 2015-11-21 08:16
I tried your code but it seems it blinks cursor even when I don't set blinkcursor.
It is like cursor blinking with light color and dark color.

**Comment by pebble8888** [comment] 2015-11-21 11:24
Thank you for your comment. I got blink cursor specification.
I pushed `fix_882_2` branch.
I only convereted the drawing logic to the earlier logic.
I don't know why this logic fix the problem precisely.
No problem for playground view.
If another bug exists, please tell me.

BTW, for scrolling cursor square blink with dark and black color when blink cursor isn't set.
This bug is another problem, so we should it by new issue.

**Comment by floorish** [comment] 2015-11-21 12:38
@pebble8888 Thanks for your work!
`fix_882` does seem to solve the problem, `fix_882_2` however does *not* fix the issue for me.

I don't really understand how the method swizzling works, but inside `xvim_drawRect:` you call
`[self xvim_drawRect:dirtyRect];`

So you call the same method, why isn't that a recursive loop? Without that the whole textview won't render, which makes me believe that it calls the original xcode `drawRect`, is that correct?

**Comment by pebble8888** [comment] 2015-11-22 07:21
@floorish 
Thanks for your confirming.

I confirmed `fix_882_2` doesn't fix the problem.
I modifed `fix_882_2` branch a bit.
If you have some time, please check it.

>edit: wait, it just switches the new and original method right?

right

**Comment by floorish** [comment] 2015-11-22 11:40
@pebble8888 checked it and seems ok!
Will do some more testing tomorrow, but for now it looks like the edited `fix_882_2` branch fixes it!

**Comment by JugglerShu** [comment] 2015-12-01 14:45
@pebble8888 
I tried your `fix_882_2` . It mainly works well but it still has a problem when you are editing in playground.
It shows blinking cursor when `blinkcursor` is not set.
The `blinking` is not complete blinking but it is again blinking with light color and dark color.

I don't want to leave cursor related program incomplete anymore since we have been working on this a long time and incomplete fix leads another issues again and again. So I'll investigate this more to complete this.

**Comment by pebble8888** [comment] 2015-12-05 08:25
@JugglerShu 
Thanks for your check.

I amended `fix_882_2` branch.
I checked blinkcursor and non-blinkcursor behavior for DVTSourceTextView and IDEPlaygroundTextView for Xcode7.1.1.
And the cursor blinking bug while scrolling disappear.
I can't eat dogfood often because I didn't use Xcode these days. 
I'm happy if this patch helps your investigation.

**Comment by keith** [comment] 2016-02-14 02:56
I haven't seen this in a while so I assume it's been fixed in one of the linked issues. Thanks!

**Comment by wiruzx** [comment] 2016-02-18 23:02
Just made a build from develop. Issue still exist for me.

**Comment by JugglerShu** [comment] 2016-03-04 13:04
I have just merged the fix in develop branch. Try to use it and give us a feedback.

**Comment by wiruzx** [comment] 2016-03-04 16:53
I just checked and issue is gone! Thanks!

**Comment by floorish** [comment] 2016-03-05 14:04
Looks good 👍 (tested on 10.11)

**Comment by floorish** [comment] 2016-03-11 11:51
@JugglerShu before you merge this into master, it seems like this fix introduces another bug which causes Xcode to crash (reproducible):

1. open a file
2. scroll to bottom
3. highlight some lines on the bottom of the file (exclude the last line)
4. press 'd' to delete those lines
5. **visual bug**: Xcode line numbers are wrong and the view does not scroll up (i.e. there are a few blank lines left on the bottom of the file)
6. go to another file in navigator
7. go back to original file in navigator
8. **Xcode crash**

````
UNCAUGHT EXCEPTION (NSInternalInconsistencyException): -[DVTLayoutManager _fillGlyphHoleForCharacterRange:startGlyphIndex:desiredNumberOfCharacters:] *** attempted glyph generation while textStorage is editing.  It is not valid to cause the layoutManager to do glyph generation while the textStorage is editing (ie the textStorage has been sent a beginEditing message without a matching endEditing.)
````

I cannot reproduce this on 11fbc0e62e39ef67ecfc5170d90e88135f297c46 (the commit before merging pebble8888/fix_882_3)

**Comment by wiruzx** [comment] 2016-03-11 12:38
@floorish Yep, exactly the same for me

**Comment by JugglerShu** [comment] 2016-03-12 05:29
Thank you for the feedback.
I won't merge the latest PR to the master.

I'm working on other problems now so I can't work on this soon but after that I'll work on this.

**Comment by pebble8888** [comment] 2016-03-14 04:07
I have been reproduced @floorish's behavior on MacBook Pro 2012 and haven't on my MacBookAir 2015.
My approach looks bad.
Anyway please revert my PR.

**Comment by pebble8888** [comment] 2016-03-25 13:56
I found a workaround to redraw visible area during scrolling.
I changed copiesOnScroll property of NSClipView to NO.
Please try.

https://github.com/pebble8888/XVim/commit/c8c32ead761c3dd337f8d8b1a28c60fb9c18d4fe

**Comment by wiruzx** [comment] 2016-03-25 14:05
So far so good

**Comment by floorish** [comment] 2016-03-29 09:38
Yep, looks good here as well

**Comment by JugglerShu** [comment] 2016-03-29 16:33
I merged @pebble8888's fix do develop branch.

**Closed** 2016-06-16 16:19 UTC
